services:
  mysqldb:
    container_name: mysql-db1
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examdb205
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"

  backend:
    container_name: backend
    build:
      context: ./BACKEND
      dockerfile: ../BACKEND/backend.Dockerfile
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./FRONTEND
      dockerfile: ../FRONTEND/frontend.Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
